image:
    repository: micnotppasacr01.azurecr.io/streams-to-event-hub
    tag: latest
    pullPolicy: Always

replicaCount: 1

resources:
    limits:
        memory: 512Mi
        cpu: '1'
    requests:
        memory: 512Mi
        cpu: '1'

service:
    name: streams-to-event-hub
    port: 80
    targetPort: 4000

sourceStreamsUrl: 'ws://discovery-streams.urban-os/socket/websocket'
streamsTopic: 'streaming:ben_andi_org_may17_22__cve_may17_2022_two'
