apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SOURCE_STREAMS_URL
          value: {{ quote .Values.sourceStreamsUrl }}
        - name: EVENT_HUB_URL
          valueFrom:
            secretKeyRef:
              name: event-hub-url
              key: event-hub-url
        - name: STREAMS_API_KEY
          valueFrom:
            secretKeyRef:
              name: streams-api-key
              key: streams-api-key
        - name: STREAMS_TOPIC
          value: {{ quote .Values.streamsTopic }}
