image:
    repository: smartcitiesdata/streams-to-event-hub
    tag: latest
    pullPolicy: Always

replicaCount: 1

resources:
    limits:
        memory: 400M
        cpu: 400m
    requests:
        memory: 400M
        cpu: 400m

service:
    name: streams-to-event-hub
    port: 80
    targetPort: 4000

sourceStreamsUrl: 'wss://streams.demo-urban-os.com/socket/websocket'
streamsTopic: 'streaming:traffic_center__connected_vehicle_live_data'
