image:
    repository: smartcitiesdata/streams-to-event-hub
    tag: 0.0.6 # increment this value when making chart changes, a new docker
    # image at this tag will then be published. Also change in Chart.yaml to
    # keep in lockstep.
    pullPolicy: Always

replicaCount: 1

resources:
    limits:
        memory: 400M
        cpu: 400m
    requests:
        memory: 400M
        cpu: 400m

service:
    name: streams-to-event-hub
    port: 80
    targetPort: 4000

sourceStreamsUrl: ''
streamsTopic: ''
